### ISSUE TITLE
Help to run 

### ISSUE THREAD

**Issue by dbmello75** [PyramidTechnologies/Python-RS-232#6]
Hi, I'm trying to access a MEI scn6628R USB. I'm using the serial COM1. But I'm getting this error. 

C:\Python27>python main.py COM1
Starting RS-232 Master on port COM1

    H or ? to show Help
    Q or CTRL+C to Quit

    V - Enable Verbose mode

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\host.py", line 143, in _serial_runner
    ser = serial.Serial(
AttributeError: 'module' object has no attribute 'Serial'

Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(sys.argv[1])

**Comment by dbmello75** [comment]
Hi, I was able to make it work with Python 3 and USB. 
[Bill_acceptor.zip](https://github.com/PyramidTechnologies/Python-RS-232/files/13653600/Bill_acceptor.zip)

**Comment by dbmello75** [comment]
Thank you.
